name: Turbo deploy to EC2

on:
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Instalar key para que el agent SSH del runner pueda ejecutar commandos de docker usando ssh
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.7.0
      with:
        key: ${{ secrets.SSH_AWS_KEY }}
        known_hosts: unnecessary
        # name: id_rsa # optional
        # config: ${{ secrets.CONFIG }} # ssh_config; optional
        # if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
    
    - name: Checkout of chat engine
      uses: actions/checkout@v4

    - name: Build and save image
      run: |
        docker build -t ${{github.event.repository.name}}:latest --no-cache .
        docker save ${{github.event.repository.name}}:latest -o ${{github.event.repository.name}}.tar

    # Copiamos al remoto la imagen y un .yml que solo recrea los contenedores con las imagenes que hay en el systema
    - name: SCP image to remote
      run: |
       scp ${{github.event.repository.name}}.tar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu/PPF
       scp docker-compose.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu/PPF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        USERNAME: ${{ secrets.USERNAME }}
        HOST: ${{ secrets.HOST }}

    # Si el ssh agent de github esta bien configurado los comandos de docker
    # deberian ejecutarse en el contexto configurado (el remote)
    - name: Compose Up in remote
      run: |
       # to just run docker commands a context must exist and be used
       docker context create remote --docker "host=ssh://${{ secrets.USERNAME }}@${{ secrets.HOST }}"
       docker context use remote
       docker load -i /home/ubuntu/PPF/${{github.event.repository.name}}.tar
       docker compose up chat-engine -d
