name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.7.0
      with:
        key: ${{ secrets.SSH_AWS_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        # name: id_rsa # optional
        # config: ${{ secrets.CONFIG }} # ssh_config; optional
        # if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
            
    
    - uses: actions/checkout@v4
    - name: Build with docker comPSOE
      run: docker compose -f "docker-compose.build.yml" build # produces images

    - name: Saving image into a tarred archive
      run: docker save ${{github.event.repository.name}}:latest -o ${{github.event.repository.name}}.tar

    - name: SCP image to remote
      run: |
       scp ${{github.event.repository.name}}.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu/PPF
       scp docker-compose.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu/PPF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        USERNAME: ${{ secrets.USERNAME }}
        HOST: ${{ secrets.HOST }}

    - name: Compose Up in remote
      run: |
       # to just run docker commands a context must exist and be used
       docker context create remote --docker "host=ssh://${{ secrets.USERNAME }}@${{ secrets.HOST }}"
       docker context use remote
       docker load -i /home/ubuntu/PPF/${{github.event.repository.name}}.tar
       docker compose up chat-engine -d

